version: "3.8"
services:
  node-app:
    # build:
    #   context: PATH
    #   dockerfile: Dockerfile
    image: hallucina-service:latest
    environment:
      - AWS_ACCESS_KEY_ID=test
      - SECRET_ACCESS_KEY=test
      - AWS_S3_REGION=test
      - BUCKET_NAME=test
      - HOST=test
      - PORT=test
      - JWT_SECRET_KEY=test
      - JWT_REFRESH_KEY=test
      - MONGO_URL=test
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - my-network

volumes:
  mongo-data:
    driver: local
